### ISSUE TITLE
Do you have circuit

### ISSUE THREAD

**Issue by harymk** [the-real-mcarn/PT6302#2]
I need circuit

**Comment by the-real-mcarn** [comment]
Hi,

Thanks for checking out my repo, in order to help you I'm going to need some more info; Which part of the circuit do you need? Between the MCU and the IC or the IC and your VFD tube? Did you read the [datasheet for the ic](https://www.alldatasheet.com/datasheet-pdf/pdf/167606/PTC/PT6302.html)? It also contains an example circuit. 

Have a nice day!
